-- MySQL Script generated by MySQL Workbench
-- Mon May 22 19:50:59 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- Drop schema if exists project_tarefa
DROP SCHEMA IF EXISTS `project_tarefa`;

-- Create schema project_tarefa
CREATE SCHEMA IF NOT EXISTS `project_tarefa` DEFAULT CHARACTER SET utf8;
USE `project_tarefa`;

-- Create table usuario
CREATE TABLE IF NOT EXISTS `usuario` (
  `id_usuario` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`)
)
ENGINE = InnoDB;

-- Create table tarefa
CREATE TABLE IF NOT EXISTS `tarefa` (
  `id_tarefa` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `prazo` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_tarefa`),
  INDEX `fk_tarefa_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_tarefa_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;

-- Create table login
CREATE TABLE IF NOT EXISTS `login` (
  `id_login` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_login`),
  CONSTRAINT `fk_login_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


-- Listar todas as tarefas vinculadas a um usuário pelo ID
-- SELECT tarefa.*
-- FROM tarefa
-- INNER JOIN usuario ON tarefa.usuario_id_usuario = usuario.id_usuario
-- WHERE usuario.id_usuario = <id_do_usuario>;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
